name: Email Step Example

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2001049@ds.study.iitm.ac.in
        run: echo "Hello, world!"
